[project]
authors = ["a1exmozz <187176404+a1exmozz@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "100-days-of-Mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0.dev2024120805,<25"
